website/models.py
from . import db
from flask_login import UserMixin


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(), unique=True)
    password = db.Column(db.String())
    admin_first = db.Column(db.String())
    admin_last = db.Column(db.String())
    member = db.relationship('Member')


class Member(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    member_first = db.Column(db.String())
    member_last = db.Column(db.String())
    member_email = db.Column(db.String(), unique=True)
    member_address = db.Column(db.String())
    category = db.Column(db.String())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager


db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'secretkey'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Member

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        with app.app_context():
            db.create_all()
        print('Created database! ')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, current_user, logout_user, login_required

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in succesffully.', category='success')
                login_user(user, remember=False)
            redirect(url_for('views.home'))
    return render_template('login.html', user=current_user)


@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        password2 = request.form.get('password2')
        admin_first = request.form.get('admin_first')
        admin_last = request.form.get('admin_last')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')

        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(admin_first) < 2:
            flash('First name must be greater than 1 character', category='error')
        elif len(admin_last) < 2:
            flash('Last name must be greater than 1 character', category='error')
        elif password != password2:
            flash('Passwords don\'t match', category='error')
        else:
            new_user = User(email=email, admin_first=admin_first, admin_last=admin_last, password=generate_password_hash(password, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))
    return render_template('register.html', user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import Member
from sqlalchemy import or_
from . import db
from flask_login import current_user

views = Blueprint('views', __name__)


@views.route('/search', methods=['GET', 'POST'])
def search():
    members = []
    search = request.args.get('search')
    if search:
        members = Member.query.filter(or_(Member.member_first.like(f"%{search}%"),
                                           Member.member_last.like(f"%{search}%"))).all()
    return render_template('search.html', members=members, user=current_user)


@views.route('/', methods=['GET', 'POST'])
def home():
    return render_template('index.html', user=current_user)


@views.route('/input', methods=['GET', 'POST'])
def input():
    if request.method == 'POST':
        member_first = request.form.get('member_first')
        member_last = request.form.get('member_last')
        member_email = request.form.get('member_email')
        member_address = request.form.get('member_address')
        category = request.form.get('category')

        member = Member.query.filter_by(member_email=member_email).first()
        if member:
            flash('Member already in database.', category='error')
        else:
            new_member = Member(member_first=member_first, member_last=member_last,
                                member_email=member_email, member_address=member_address,
                                category=category, user_id=current_user.id)
            db.session.add(new_member)
            db.session.commit()
            flash('Member added!', category='success')
        return redirect((url_for('views.home')))
    return render_template('input.html', user=current_user)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
    />
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            crossorigin="anonymous"
    />
    <title>{% block title %}{% endblock %}</title>

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <!--    Fits it for a mobile-->
    <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbar"
    >
        <!--        Adds an icon on the nav bar -->
        <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">

            <a class="nav-item nav-link" id="home" href="/">Home</a>
            <a class="nav-item nav-link" id="register" href="/login">Login</a>
            <a class="nav-item nav-link" id="login" href="/register">Register</a>
            <a class="nav-item nav-link" id="signUp" href="/search">Search</a>
            {% if user.is_authenticated %}

            <a class="nav-item nav-link" id="input" href="/input">Input</a>
            <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
            {% endif %}
        </div>
    </div>
</nav>

{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
{% if category == 'error' %}
<div class="alert alert-danger alter-dismissable fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% else %}
<div class="alert alert-success alter-dismissable fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %} {% endfor %} {% endif %} {% endwith %}

<div class="container">{% block content %} {% endblock %}</div>
<script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"
></script>
<script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
></script>
<script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"
></script>

<script type="text/javascript" src="{{ url_for('static', filename='index.js') }}">
</script>

{% block javascript %}
<script type="text/javascript">
      function deleteNote(noteId) {
  fetch("/delete-note", {
    method: "POST",
    body: JSON.stringify({ noteId: noteId }),
  }).then((_res) => {
    window.location.href = "/";
  });
  }
</script>
{% endblock %}





</body>
</html>

website/templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="text-center">
<h1>Search Records</h1>
    <p>Search student and faculty records here.</p>

    <a class="link" id="login" href="/login">Login</a><br>
    <a class="link" id="register" href="/register">Register</a><br>



</div>
{% endblock %}

website/templates/input.html
{% extends 'base.html' %}

{% block title %}Input{% endblock %}

{% block content %}
<form method="POST">
    <h3>Input a User into Database</h3>

    <div class="form-group">
        <label for="member_first">Member's First Name</label>
        <input type="text" class="form-control" id="member_first" name="member_first" placeholder="Member's First Name">
    </div>

    <div class="form-group">
        <label for="member_last">Member's Last Name</label>
        <input type="text" class="form-control" id="member_last" name="member_last" placeholder="Member's Last Name">
    </div>

    <div class="form-group">
        <label for="member_first">Member's Email Name</label>
        <input type="text" class="form-control" id="member_email" name="member_email" placeholder="Member's Email">
    </div>

    <div class="form-group">
        <label for="member_address">Member's Address</label>
        <input type="text" class="form-control" id="member_address" name="member_address" placeholder="Member's Address">
    </div>

    <div class="form-group">
        <label for="category">Select Category</label><br>
        <select id="category" name="category">
            <option value="student">Student</option>
            <option value="faculty">Faculty</option>
            <option value="staff">Staff</option>
        </select>
    </div>

    <br>
    <button type="submit" class="btn btn-primary">Submit</button>




</form>

{% endblock %}

website/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
    </div>

    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter your password">
    </div>

    <button type="submit" class="btn btn-primary">Login</button>

</form>
{% endblock %}

website/templates/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
<form method="POST">
    <h3>Register</h3>

    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="text" class="form-control" id="email" name="email" placeholder="Enter email">
    </div>

    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter password">
    </div>

    <div class="form-group">
        <label for="password2">Confirm Password</label>
        <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm password">
    </div>

    <div class="form-group">
        <label for="admin_first">First Name</label>
        <input type="text" class="form-control" id="admin_first" name="admin_first" placeholder="Enter first name">
    </div>

    <div class="form-group">
        <label for="admin_last">Last Name</label>
        <input type="text" class="form-control" id="admin_last" name="admin_last" placeholder="Enter last name">
    </div>

    <br>
    <button type="submit" class="btn btn-primary">Submit</button>

</form>
{% endblock %}

website/templates/search.html
{% extends 'base.html' %}

{% block title %}Search{% endblock %}

{% block content %}
<div class="text-center">
<h2>Search Content</h2>
<form method="get" action="{{ url_for('views.search') }}"><br>
    <input type="text" name="search" id="search" required><br><br>
    <input type="submit" value="Search"><br>
</form>
<br>
<h2>Results</h2>
<div class="row justify-content-center">
    <div class="col-auto">

    <table class="table table-responsive">
    <tr>
        <th>First</th>
        <th>Last</th>
        <th>Email</th>
        <th>Address</th>
        <th>Category</th>
    </tr>
    {% for member in members %}
    <tr>
        <td>{{ member.member_first }}</td>
        <td>{{ member.member_last }}</td>
        <td>{{ member.member_email }}</td>
        <td>{{ member.member_address }}</td>
        <td>{{ member.category }}</td>

    </tr>
    {% endfor %}
</table>
    </div>

</div>
</div>
{% endblock %}